name: release 

on:
  push:
    branches:
      - stable-release
      
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry build system and dependencies
        run: |
          export POETRY_VIRTUALENVS_CREATE=false
          pip install -U pip 
          pip install poetry
          poetry config http-basic.fury ${{ secrets.GEMFURY_DEPLOY_TOKEN }} NOPASS
          poetry install
      
      - name: Run tests
        run: |  
          pytest

      - name: Build release 
        run: | 
          poetry build

      - name: Deploy package to GemFury 
        run: |
          export GEMFURY_PUSH_TOKEN=${{ secrets.GEMFURY_PUSH_TOKEN }} 
          "${GITHUB_WORKSPACE}/.github/publish.sh"

      - name: Create version tag environment variable
        run: |
          pip install toml
          python ${GITHUB_WORKSPACE}/.github/version_tag.py >> $GITHUB_ENV
      
      - name: Check tag
        run: | 
          echo $VERSION_TAG
          echo ${{ env.VERSION_TAG}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION_TAG }}
          release_name: v${{ env.VERSION_TAG }}
          draft: false
          prerelease: false